### ISSUE TITLE
angular-owl-carousel.js bower script is not added by bower/grunt in the index.html 

### ISSUE THREAD

**Issue by gabrielruiz** [fatuk/angular-owl-carousel1#1]
The issue happen when the app try to load the script angular-owl-carousel.js to the main (index.html).

It happen because the bower.json file try to load the file src/angular-owl-carousel1.js but this name is wrong, the correct name is src/angular-owl-carousel.js. 

Please fix it in bower.json and .bower.json:
{
...
   "main": "src/angular-owl-carousel1.js" // it is a wrong name
...
}

Thanks in advance.

**Comment by fatuk** [comment]
Done. Thanks :+1:
